name: foodytn
description: A Tunisian Restaurant Discovery App.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2

  cupertino_icons: ^1.0.6
  # Added for UI and Logic
  font_awesome_flutter: ^10.6.0
  google_fonts: ^7.1.0
  http: ^1.2.0

  path: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true


  assets:

    - assets/images/